"""Pytest suite for heliogram codec v0.1: clean roundtrip exactness, determinism, and calibration
recovery under a mild global color shift. Assert-based, no fixtures.

Also covers the Slice-A capacity-ceiling additions: palettes 32/64 (exercised automatically since
the palette-driven tests below iterate VALID_PALETTES, which now includes them) and sub-patch
packing (`subpatch`/k, explicit cases only -- see the `subpatch` section at the bottom). All
numbers in this file come from `decode_pixels`, the model-free reference decoder (see
heliogram/codec.py's module docstring) -- nothing here is a VLM/Phase-2 result.

Also covers real (not synthetic-pixel-shift) corruption via heliogram.corruption -- see the
"realistic corruption coverage" section near the bottom, which pins measured decode
success/failure for palette 32/64 (subpatch=1) and every SUBPATCH_PALETTES entry (subpatch=2)
under actual resize/JPEG/crop round-trips, mirroring (a subset of) heliogram.harness.CORRUPTIONS.
"""

import hashlib
import io
import json

import numpy as np
from PIL import Image

from heliogram import decode_pixels, encode, get_palette
from heliogram.codec import HeliogramDecodeError, VALID_PALETTES, VALID_SUBPATCHES
from heliogram.corruption import compose, crop_pad, jpeg_compress, resize_roundtrip
from heliogram.dataset import random_payload

PAYLOADS = [
    b"",
    b"a",
    b"hello, heliogram!",
    json.dumps(
        {"id": 42, "name": "heliogram", "tags": ["vlm", "codec"], "active": True}
    ).encode("utf-8"),
    bytes(range(256)) * 2,  # 512 bytes; exercises reedsolo's internal chunking
]

# Palettes explicitly named in the Slice-A task for the new subpatch=2 coverage.
SUBPATCH_PALETTES = (8, 16, 32, 64)

# Real (not synthetic-pixel-shift) corruptions, mirroring the mild end of
# heliogram.harness.CORRUPTIONS' "realistic serving pipeline" envelope (resize +-3-5%, JPEG
# q95/85, slight crop/pad). Empirically confirmed (see results.csv / RESULTS.md, generated by
# heliogram.harness's own sweep) to give decode_success_rate=1.00 for every palette in
# VALID_PALETTES, both subpatch=1 and subpatch=2, at every payload size the sweep covers --
# unlike jpeg_q70/"combined", which are NOT reliable at every (palette, payload_size) and are
# covered separately below by tests that pin the measured *failure* rather than assume success.
REALISTIC_MILD_CORRUPTIONS = {
    "resize_3pct": lambda img: resize_roundtrip(img, scale=0.97),
    "resize_5pct": lambda img: resize_roundtrip(img, scale=0.95),
    "jpeg_q95": lambda img: jpeg_compress(img, quality=95),
    "crop_pad_2px": lambda img: crop_pad(img, dx=2, dy=2),
}


def _png_bytes(img: Image.Image) -> bytes:
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def test_clean_roundtrip_exact():
    for palette in VALID_PALETTES:
        for payload in PAYLOADS:
            img = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0)
            recovered = decode_pixels(img, palette=palette, patch_size=14, nsym=32)
            assert recovered == payload, (
                f"roundtrip mismatch for palette={palette} payload_len={len(payload)}"
            )


def test_determinism_same_args_identical_png_bytes():
    payload = b"determinism check: heliogram v0.1"
    for palette in VALID_PALETTES:
        img1 = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0)
        img2 = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0)
        assert _png_bytes(img1) == _png_bytes(img2)


def test_determinism_different_payload_differs():
    img1 = encode(b"payload one", palette=8)
    img2 = encode(b"payload two", palette=8)
    assert _png_bytes(img1) != _png_bytes(img2)


def test_calibration_recovery_under_mild_global_color_shift():
    shift = np.array([6, -4, 5], dtype=np.int16)
    for palette in VALID_PALETTES:
        payload = f"calibration test palette={palette}".encode("utf-8")
        img = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0)
        arr = np.asarray(img, dtype=np.int16)
        shifted = np.clip(arr + shift, 0, 255).astype(np.uint8)
        shifted_img = Image.fromarray(shifted)
        recovered = decode_pixels(shifted_img, palette=palette, patch_size=14, nsym=32)
        assert recovered == payload, f"calibration recovery failed for palette={palette}"


def test_palette_deterministic_and_separable():
    for palette in VALID_PALETTES:
        colors_a = get_palette(palette)
        colors_b = get_palette(palette)
        assert colors_a == colors_b
        assert len(set(colors_a)) == palette  # all colors distinct -- incl. get_palette(64)


# --- subpatch (k>1 sub-patch packing, Slice A) ---------------------------------------------
#
# These are geometric/decode_pixels-only checks: subpatch>1 raises how many symbols a pixel
# decoder can read out of a patch, not what a real ViT-patch VLM encoder could resolve (see
# heliogram/codec.py's module docstring and spec/format-v0.1.md section 6a). No claim here
# about model capability, only about the reference decoder's exact roundtrip.


def test_subpatch2_clean_roundtrip_exact():
    for palette in SUBPATCH_PALETTES:
        for payload in PAYLOADS:
            img = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0, subpatch=2)
            recovered = decode_pixels(img, palette=palette, patch_size=14, nsym=32, subpatch=2)
            assert recovered == payload, (
                f"subpatch=2 roundtrip mismatch for palette={palette} payload_len={len(payload)}"
            )


def test_subpatch2_determinism_same_args_identical_png_bytes():
    payload = b"determinism check: heliogram subpatch=2"
    for palette in SUBPATCH_PALETTES:
        img1 = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0, subpatch=2)
        img2 = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0, subpatch=2)
        assert _png_bytes(img1) == _png_bytes(img2)


def test_subpatch1_output_unchanged_pinned_hash():
    """Guard back-compat: subpatch=1 (the default) must reproduce the exact pre-subpatch v0.1
    byte stream. These SHA-256 digests were captured from `encode()` at the commit immediately
    before sub-patch packing was introduced (git HEAD at the time this test was added) and
    independently re-verified byte-for-byte against that same pre-change implementation -- they
    pin the real historical output, not just whatever the current code happens to produce.
    """
    payload = b"heliogram v0.1 subpatch=1 back-compat guard"
    expected_sha256 = {
        8: "7683a171f5bc500ebd059f13abed3d34c0ab7059c5a5031db04ff7e47606cea2",
        16: "a5420a89d9c35bb2376da2cb81645a5ce6396a4c243a3afa067506bd29e69b34",
    }
    for palette, digest in expected_sha256.items():
        img_default = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0)
        img_explicit = encode(
            payload, palette=palette, patch_size=14, nsym=32, seed=0, subpatch=1
        )
        png_default = _png_bytes(img_default)
        png_explicit = _png_bytes(img_explicit)
        assert png_default == png_explicit, (
            f"default subpatch differs from explicit subpatch=1 for palette={palette}"
        )
        assert hashlib.sha256(png_default).hexdigest() == digest, (
            f"subpatch=1 PNG bytes changed for palette={palette} -- back-compat break"
        )


def test_subpatch_invalid_values_raise_value_error():
    assert VALID_SUBPATCHES == (1, 2)
    try:
        encode(b"x", palette=8, patch_size=14, subpatch=3)
        assert False, "expected ValueError for subpatch=3"
    except ValueError:
        pass
    try:
        encode(b"x", palette=8, patch_size=15, subpatch=2)  # 15 % 2 != 0
        assert False, "expected ValueError for patch_size not divisible by subpatch"
    except ValueError:
        pass


# --- realistic corruption coverage (review-fix) --------------------------------------------
#
# Everything above either used a clean image or a synthetic +-6/-4/+5 RGB shift
# (test_calibration_recovery_under_mild_global_color_shift) -- never a real resize/JPEG/crop
# round-trip, and subpatch=2 had NO corruption coverage of any kind. That was an adequate proxy
# for palettes 2/4/8/16 (they survive the full realistic envelope in results.csv/RESULTS.md
# almost everywhere), but it stopped being one once VALID_PALETTES grew to include 32/64 and
# subpatch grew to include 2: the harness's own measured sweep shows both of those genuinely
# fail decode under corruptions it classifies as "realistic" (not just the STRESS_CORRUPTIONS
# diagnostic suite), at specific (payload_size, corruption) combinations. The tests below use
# heliogram.corruption's real primitives (not pixel-shift synthesis) and, per this project's
# DATA HONESTY rule, pin the TRUE measured outcome in each direction: success where the harness
# shows success, and failure where it shows failure -- see each test's docstring for the exact
# results.csv row it reproduces.


def test_realistic_mild_corruption_roundtrip_all_palettes_subpatch1():
    """Closes the gap: no prior test applied a real resize/JPEG/crop corruption to ANY palette
    (only a synthetic global color shift). Empirically verified against results.csv: every
    palette in VALID_PALETTES (including 32/64) decodes successfully under this mild-realistic
    corruption set at every payload size the harness sweep covers -- this is the regime where
    the old clean+shift methodology's conclusion ("robust") actually still holds for 32/64, so
    pin it explicitly instead of leaving it untested."""
    for palette in VALID_PALETTES:
        for payload in PAYLOADS:
            img = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0)
            for name, corrupt in REALISTIC_MILD_CORRUPTIONS.items():
                corrupted = corrupt(img)
                recovered = decode_pixels(corrupted, palette=palette, patch_size=14, nsym=32)
                assert recovered == payload, (
                    f"subpatch=1 decode failed under realistic corruption={name} for "
                    f"palette={palette} payload_len={len(payload)}"
                )


def test_palette32_64_known_failure_under_jpeg_q70_at_scale():
    """DATA HONESTY: pins a MEASURED failure, not a hypothetical one -- see results.csv rows
    'palette=32,subpatch=1,payload_size=1024,corruption=jpeg_q70' and
    'palette=64,subpatch=1,payload_size=1024,corruption=jpeg_q70', both decode_success_rate=
    0.0000. This is the exact gap Finding #2 flagged: extending VALID_PALETTES to 32/64 without
    ANY real-corruption test meant a future change to get_palette's P>16 value-tiling scheme
    (v_min floor, hues=16 split) could silently make this better or worse and no assertion would
    move. Uses heliogram.dataset.random_payload -- the same deterministic construction
    heliogram.harness._random_payload uses for trial seed=0 -- so this reproduces the harness's
    own measured cell exactly, at the same payload_size=1024 the finding cites.

    If this test ever starts failing because decode now SUCCEEDS, that is a genuine robustness
    improvement to get_palette/decode_pixels for P>16 -- update this test (and re-run
    heliogram.harness to refresh RESULTS.md/results.csv) rather than just deleting the
    assertion; do not silently paper over a real behavior change either way.
    """
    payload = random_payload(0, 1024)
    for palette in (32, 64):
        img = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0)
        corrupted = jpeg_compress(img, quality=70)
        try:
            recovered = decode_pixels(corrupted, palette=palette, patch_size=14, nsym=32)
        except HeliogramDecodeError:
            continue  # expected: RS could not correct -- the measured failure mode
        assert recovered != payload, (
            f"palette={palette} subpatch=1 unexpectedly recovered the exact payload under "
            "jpeg_q70 at payload_size=1024 -- this contradicts the measured "
            "decode_success_rate=0.0000 in results.csv for this exact cell; if genuine, "
            "update RESULTS.md/results.csv (re-run heliogram.harness) and this test together"
        )


def test_subpatch2_roundtrip_under_realistic_mild_corruption():
    """CRITICAL review-fix: prior to this test, subpatch=2 had zero coverage against ANY
    corruption -- test_subpatch2_clean_roundtrip_exact only ever used a clean image. This pins
    the mild end of the realistic corruption envelope (resize +-3-5%, JPEG q95, 2px crop/pad --
    plus jpeg_q85, separately confirmed reliable for subpatch=2 in results.csv/RESULTS.md at
    every tested payload size) as an exact-roundtrip regression guard: a future change to
    extract_symbols' sub-cell sampling geometry (`sub_half`, sub-cell layout order, etc.) that
    broke decoding here would now be caught, where previously it would not have been."""
    corruptions = dict(REALISTIC_MILD_CORRUPTIONS)
    corruptions["jpeg_q85"] = lambda img: jpeg_compress(img, quality=85)
    for palette in SUBPATCH_PALETTES:
        for payload in PAYLOADS:
            img = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0, subpatch=2)
            for name, corrupt in corruptions.items():
                corrupted = corrupt(img)
                recovered = decode_pixels(
                    corrupted, palette=palette, patch_size=14, nsym=32, subpatch=2
                )
                assert recovered == payload, (
                    f"subpatch=2 decode failed under realistic corruption={name} for "
                    f"palette={palette} payload_len={len(payload)}"
                )


def test_subpatch2_known_failure_under_combined_corruption_small_payload():
    """DATA HONESTY: pins a MEASURED failure, not a hypothetical one -- see results.csv rows
    'palette={8,16,32,64},subpatch=2,payload_size=48,corruption=combined', ALL
    decode_success_rate=0.0000. 'combined' (resize 5% + JPEG q70 + 2px crop/pad in sequence) is
    part of heliogram.harness.CORRUPTIONS -- the "realistic serving pipeline" suite, not the
    STRESS_CORRUPTIONS diagnostic-only suite -- so this is a genuine, currently-measured
    limitation of subpatch=2 at this payload size, not a manufactured edge case. Uses
    heliogram.dataset.random_payload(0, 48) -- the same construction heliogram.harness uses for
    trial seed=0 at payload_size=48 -- to reproduce the harness's own measured cell exactly.

    This is a regression guard in the OTHER direction from most of this file: if it starts
    failing because decode now SUCCEEDS, that is a genuine improvement -- update this test (and
    re-run heliogram.harness to refresh RESULTS.md/results.csv) rather than silencing it; a
    future change to sub-cell sampling could just as easily make this (or a currently-passing
    subpatch=2 case) silently WORSE, which is exactly the coverage gap this test and
    test_subpatch2_roundtrip_under_realistic_mild_corruption together close.
    """
    payload = random_payload(0, 48)
    for palette in SUBPATCH_PALETTES:
        img = encode(payload, palette=palette, patch_size=14, nsym=32, seed=0, subpatch=2)
        corrupted = compose(
            img,
            [
                (resize_roundtrip, {"scale": 0.95}),
                (jpeg_compress, {"quality": 70}),
                (crop_pad, {"dx": 2, "dy": 2}),
            ],
        )
        try:
            recovered = decode_pixels(corrupted, palette=palette, patch_size=14, nsym=32, subpatch=2)
        except HeliogramDecodeError:
            continue  # expected: RS could not correct -- the measured failure mode
        assert recovered != payload, (
            f"palette={palette} subpatch=2 unexpectedly recovered the exact payload under "
            "'combined' corruption at payload_size=48 -- this contradicts the measured "
            "decode_success_rate=0.0000 in results.csv for this exact cell; if genuine, "
            "update RESULTS.md/results.csv (re-run heliogram.harness) and this test together"
        )
