#!/usr/bin/env bash
# scripts/smoke.sh -- the model-free, no-GPU end-to-end repro check ("make smoke").
#
# WHAT THIS DOES: runs the model-free pytest suite, then runs the model-free CLIs
# (heliogram.benefit, heliogram.instruments.foreign_tile, heliogram.typography, plus --help for
# the two GPU-only scripts, which must work with zero GPU packages installed) and diffs a
# deliberately small set of VERSION-STABLE, deterministic-arithmetic lines from their output
# against committed fixtures under tests/expected/*.txt.
#
# WHAT THIS DELIBERATELY DOES NOT DO: it never diffs raw PNG/JPEG bytes, RESULTS.md, results.csv,
# probe_report*, heliogram/data/*.json, or any JPEG-decode-success-rate number -- all of those are
# Pillow-version-sensitive (see README's determinism note / .github/workflows/ci.yml's own
# comment on the Pillow-bump incident this project already had once). Every line diffed here is
# either exact integer/float arithmetic (RS error-correction budgets, token/patch counts derived
# from payload byte lengths) or a seeded, reproducible detector TPR/FPR -- none of it depends on
# which Pillow/numpy build produced it, only on the numbers themselves.
#
# Fixtures were generated BY RUNNING these exact commands in-container (never hand-authored) and
# verified to be byte-identical across two consecutive runs before being committed -- see the
# task report for the transcript of that verification.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
REPO_ROOT="$(pwd)"
EXPECTED_DIR="tests/expected"
STATUS=0

# Extended-regex line filters. Each selects ONLY lines that are pure, deterministic arithmetic or
# seeded-detector output -- see the module docstrings this script's comment above points to for
# why these specific lines are safe to pin across Pillow/numpy/Python versions.
BENEFIT_FILTER='^(heliogram patches|base64 tokens|hex \(raw-byte\) tokens|patches / (base64|hex|raw text) tokens|  ASSUMPTION|  RS correction budget|  within RS budget|  recovered_bit_fraction|  tokens spent|  cost per recovered bit):'
FOREIGN_TILE_FILTER='^TPR='
TYPOGRAPHY_FILTER='^VERDICT:'

check_fixture() {
    # check_fixture <label> <fixture-file> <actual-content>
    #
    # IMPORTANT: takes the actual content as an ARGUMENT (a variable the caller already captured
    # via command substitution), never via a pipe into this function -- a function at the tail
    # of a pipeline runs in a subshell in bash, so a `STATUS=1` assigned inside it would silently
    # vanish once the pipeline exits, leaving the top-level STATUS (and this script's exit code)
    # wrongly at 0 even after printing "FAIL". Called as a plain function invocation instead, so
    # its STATUS writes land in this script's own shell.
    local label="$1"
    local fixture="$2"
    local actual="$3"
    local diff_out
    if [[ ! -f "$fixture" ]]; then
        echo "FAIL [$label]: missing expected fixture $fixture"
        STATUS=1
        return
    fi
    if ! diff_out="$(diff -u "$fixture" <(printf '%s\n' "$actual"))"; then
        echo "FAIL [$label]: output drifted from $fixture"
        echo "$diff_out"
        STATUS=1
        return
    fi
    echo "PASS [$label]"
}

echo "############################################################"
echo "# [1/5] model-free pytest suite (python -m pytest tests/ -q)"
echo "############################################################"
set +e
PYTEST_OUT="$(python -m pytest tests/ -q 2>&1)"
PYTEST_RC=$?
set -e
echo "$PYTEST_OUT" | tail -8
if [[ $PYTEST_RC -ne 0 ]]; then
    echo "FAIL [pytest]: suite did not pass (exit $PYTEST_RC)"
    exit 1
fi
# Floor check, not an exact-count pin: the suite's exit code above already fails smoke on any
# test error/failure. This second check only guards against silent test LOSS (suite still green
# but fewer tests ran) -- so it asserts "0 failed" and "passed >= a committed floor" rather than
# an exact number, which would otherwise break on every legitimately-added or -removed test.
# `|| true`: on a green run there is no "N failed" token, so that grep matches nothing and exits
# non-zero -- without this, `set -euo pipefail` would abort the whole script on SUCCESS.
PYTEST_PASSED="$(echo "$PYTEST_OUT" | grep -oE '[0-9]+ passed' | grep -oE '[0-9]+' | head -1 || true)"
PYTEST_FAILED="$(echo "$PYTEST_OUT" | grep -oE '[0-9]+ failed' | grep -oE '[0-9]+' | head -1 || true)"
MIN_PASSED="$(tr -dc '0-9' < "$EXPECTED_DIR/pytest_min_passed.txt")"
if [[ -z "$PYTEST_PASSED" ]]; then
    echo "FAIL [pytest]: could not find a 'N passed' count in the summary"
    STATUS=1
elif [[ -n "$PYTEST_FAILED" && "$PYTEST_FAILED" -ne 0 ]]; then
    echo "FAIL [pytest]: $PYTEST_FAILED test(s) failed"
    STATUS=1
elif [[ "$PYTEST_PASSED" -lt "$MIN_PASSED" ]]; then
    echo "FAIL [pytest floor]: only $PYTEST_PASSED passed, expected >= $MIN_PASSED -- possible test loss. If you intentionally removed tests, lower tests/expected/pytest_min_passed.txt."
    STATUS=1
else
    echo "PASS [pytest]: $PYTEST_PASSED passed (>= floor $MIN_PASSED), 0 failed"
fi

echo
echo "############################################################"
echo "# [2/5] heliogram.benefit -- RS budget / token-count invariants"
echo "############################################################"
set +e
BENEFIT_OUT="$(python -m heliogram.benefit 2>&1)"
BENEFIT_RC=$?
set -e
if [[ $BENEFIT_RC -ne 0 ]]; then
    echo "FAIL [heliogram.benefit]: nonzero exit ($BENEFIT_RC)"
    echo "$BENEFIT_OUT" | tail -20
    STATUS=1
else
    set +e
    BENEFIT_INV="$(echo "$BENEFIT_OUT" | grep -E "$BENEFIT_FILTER")"
    BENEFIT_GREP_RC=$?
    set -e
    if [[ $BENEFIT_GREP_RC -ne 0 ]]; then
        echo "FAIL [heliogram.benefit invariants]: no invariant lines matched the filter -- has the output format changed?"
        STATUS=1
    else
        check_fixture "heliogram.benefit invariants" "$EXPECTED_DIR/benefit_invariants.txt" "$BENEFIT_INV"
    fi
fi

echo
echo "############################################################"
echo "# [3/5] heliogram.instruments.foreign_tile -- TPR/FPR (seed 0)"
echo "############################################################"
set +e
FOREIGN_TILE_OUT="$(python -m heliogram.instruments.foreign_tile 2>&1)"
FOREIGN_TILE_RC=$?
set -e
if [[ $FOREIGN_TILE_RC -ne 0 ]]; then
    echo "FAIL [heliogram.instruments.foreign_tile]: nonzero exit ($FOREIGN_TILE_RC)"
    echo "$FOREIGN_TILE_OUT" | tail -20
    STATUS=1
else
    set +e
    FOREIGN_TILE_INV="$(echo "$FOREIGN_TILE_OUT" | grep -E "$FOREIGN_TILE_FILTER")"
    FOREIGN_TILE_GREP_RC=$?
    set -e
    if [[ $FOREIGN_TILE_GREP_RC -ne 0 ]]; then
        echo "FAIL [heliogram.instruments.foreign_tile TPR/FPR]: no TPR= lines matched -- has the output format changed?"
        STATUS=1
    else
        check_fixture "heliogram.instruments.foreign_tile TPR/FPR" "$EXPECTED_DIR/foreign_tile_invariants.txt" "$FOREIGN_TILE_INV"
    fi
fi

echo
echo "############################################################"
echo "# [4/5] heliogram.typography -- model-free geometric de-risk gate"
echo "############################################################"
# Needs a real monospace TrueType font on the system (see _load_monospace_font's docstring in
# heliogram/typography.py -- it deliberately refuses to fall back to a proportional font). The
# Dockerfile and CI workflow both install fonts-dejavu-core for exactly this reason. Only the
# VERDICT line is diffed here -- its geometric packing TABLE depends on font advance-width
# metrics, which are stable given a pinned font file but are not one of this project's
# already-verified-stable invariants the way RS arithmetic/TPR-FPR are, so it is deliberately not
# pinned as a byte-exact fixture here.
set +e
TYPOGRAPHY_OUT="$(python -m heliogram.typography 2>&1)"
TYPOGRAPHY_RC=$?
set -e
if [[ $TYPOGRAPHY_RC -ne 0 ]]; then
    echo "FAIL [heliogram.typography]: nonzero exit ($TYPOGRAPHY_RC) -- if this is a missing-font"
    echo "RuntimeError, install a real monospace TrueType font (e.g. 'apt-get install"
    echo "fonts-dejavu-core') -- see heliogram/typography.py's _load_monospace_font docstring."
    echo "$TYPOGRAPHY_OUT" | tail -20
    STATUS=1
else
    set +e
    TYPOGRAPHY_INV="$(echo "$TYPOGRAPHY_OUT" | grep -E "$TYPOGRAPHY_FILTER")"
    TYPOGRAPHY_GREP_RC=$?
    set -e
    if [[ $TYPOGRAPHY_GREP_RC -ne 0 ]]; then
        echo "FAIL [heliogram.typography VERDICT]: no VERDICT: line matched -- has the output format changed?"
        STATUS=1
    else
        check_fixture "heliogram.typography VERDICT" "$EXPECTED_DIR/typography_verdict.txt" "$TYPOGRAPHY_INV"
    fi
fi

echo
echo "############################################################"
echo "# [5/5] GPU-only script entry points refuse-without-model (help only, no GPU/model needed)"
echo "############################################################"
if python scripts/run_probe.py --help > /dev/null 2>&1; then
    echo "PASS [run_probe.py --help]"
else
    echo "FAIL [run_probe.py --help]: nonzero exit"
    STATUS=1
fi
if python scripts/train_merger_adapter.py --help > /dev/null 2>&1; then
    echo "PASS [train_merger_adapter.py --help]"
else
    echo "FAIL [train_merger_adapter.py --help]: nonzero exit"
    STATUS=1
fi

echo
if [[ $STATUS -eq 0 ]]; then
    echo "SMOKE: PASS -- pytest suite green, all version-stable CLI invariants match committed fixtures."
else
    echo "SMOKE: FAIL -- see diffs above."
fi
exit $STATUS
